version: "2"
checks:
  file-lines:
      config:
        threshold: 500
  method-complexity:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 100
  return-statements:
      enabled: true
      config:
        threshold: 10
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: .eslintrc